CREATE TABLE "public"."GERSSON_REGISTROS" ( 
  "ID" SERIAL,
  "ID_CLIENTE" INTEGER NOT NULL,
  "TIPO_EVENTO" VARCHAR(250) NULL,
  "FECHA_EVENTO" VARCHAR(250) NULL,
  CONSTRAINT "GERSSON_REGISTROS_pkey" PRIMARY KEY ("ID")
);
CREATE TABLE "public"."gersson_admins" ( 
  "id" UUID NOT NULL DEFAULT gen_random_uuid() ,
  "nombre" TEXT NOT NULL,
  "whatsapp" TEXT NOT NULL,
  "fecha_creacion" TIMESTAMP WITH TIME ZONE NULL DEFAULT now() ,
  CONSTRAINT "gersson_admins_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "gersson_admins_whatsapp_key" UNIQUE ("whatsapp")
);
CREATE TABLE "public"."GERSSON_ASESORES" ( 
  "ID" SERIAL,
  "NOMBRE" VARCHAR(250) NOT NULL,
  "WHATSAPP" VARCHAR(250) NOT NULL,
  "LINK" INTEGER NOT NULL DEFAULT 0 ,
  "RECHAZADOS" INTEGER NOT NULL DEFAULT 0 ,
  "CARRITOS" INTEGER NOT NULL DEFAULT 0 ,
  "TICKETS" INTEGER NOT NULL DEFAULT 0 ,
  "COMPRAS" INTEGER NULL DEFAULT 0 ,
  "ES_ADMIN" BOOLEAN NULL DEFAULT false ,
  "ID_TG" VARCHAR NOT NULL,
  "MASIVOS" INTEGER NOT NULL DEFAULT 0 ,
  "FECHA_INICIO_REGLA" BIGINT NULL,
  "FECHA_FIN_REGLA" BIGINT NULL,
  "LIMITE_DIARIO" INTEGER NULL,
  "PRIORIDAD" INTEGER NULL DEFAULT 0,
  "HISTORIAL" JSON NULL,
  "PAUSADO" BOOLEAN NULL DEFAULT false,
  CONSTRAINT "GERSSON_ASESORES_pkey" PRIMARY KEY ("ID")
);
CREATE TABLE "public"."GERSSON_CLIENTES" ( 
  "ID" SERIAL,
  "NOMBRE" VARCHAR(250) NOT NULL,
  "ESTADO" VARCHAR(250) NOT NULL,
  "WHATSAPP" VARCHAR(250) NOT NULL,
  "ID_ASESOR" INTEGER NULL,
  "NOMBRE_ASESOR" VARCHAR(250) NULL,
  "WHA_ASESOR" VARCHAR(250) NULL,
  "FECHA_CREACION" VARCHAR(250) NOT NULL,
  "FECHA_COMPRA" VARCHAR(250) NULL,
  "MEDIO_COMPRA" VARCHAR(250) NULL,
  "MONTO_COMPRA" NUMERIC NULL,
  "MONEDA_COMPRA" TEXT NULL,
  "PAIS" VARCHAR(100) NULL,
  CONSTRAINT "GERSSON_CLIENTES_pkey" PRIMARY KEY ("ID")
);
CREATE TABLE "public"."GERSSON_REPORTES" ( 
  "ID" SERIAL,
  "ID_CLIENTE" INTEGER NOT NULL,
  "ID_ASESOR" INTEGER NOT NULL,
  "ESTADO_ANTERIOR" VARCHAR(250) NULL,
  "ESTADO_NUEVO" VARCHAR(250) NOT NULL,
  "COMENTARIO" TEXT NULL,
  "FECHA_REPORTE" BIGINT NULL,
  "NOMBRE_ASESOR" VARCHAR(250) NOT NULL,
  "FECHA_SEGUIMIENTO" BIGINT NULL,
  "COMPLETADO" BOOLEAN NULL,
  "IMAGEN_CONVERSACION_URL" TEXT NULL,
  "IMAGEN_PAGO_URL" TEXT NULL,
  "PAIS_CLIENTE" VARCHAR(100) NULL,
  "CORREO_INSCRIPCION" VARCHAR(255) NULL,
  "TELEFONO_CLIENTE" VARCHAR(50) NULL,
  "CORREO_PAGO" VARCHAR(255) NULL,
  "MEDIO_PAGO" VARCHAR(100) NULL,
  "TIPO_VENTA" VARCHAR NULL,
  "consolidado" BOOLEAN NULL DEFAULT false ,
  "imagen_inicio_conversacion" TEXT NULL,
  "imagen_fin_conversacion" TEXT NULL,
  "video_conversacion" TEXT NULL,
  "PRODUCTO" VARCHAR(250) NULL,
  "verificada" BOOLEAN NULL DEFAULT false ,
  "estado_verificacion" VARCHAR(250) NULL,
  "comentario_rechazo" VARCHAR(250) NULL,
  CONSTRAINT "GERSSON_REPORTES_pkey" PRIMARY KEY ("ID")
);
CREATE TABLE "public"."conversaciones" ( 
  "id" SERIAL,
  "id_asesor" INTEGER NOT NULL,
  "wha_cliente" VARCHAR(30) NOT NULL,
  "modo" VARCHAR(10) NOT NULL,
  "timestamp" BIGINT NOT NULL,
  "mensaje" TEXT NOT NULL,
  "id_cliente" INTEGER NULL,
  CONSTRAINT "conversaciones_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "idx_registros_tipo_evento" 
ON "public"."GERSSON_REGISTROS" (
  "TIPO_EVENTO" ASC
);
CREATE INDEX "idx_registros_id_cliente" 
ON "public"."GERSSON_REGISTROS" (
  "ID_CLIENTE" ASC
);
CREATE INDEX "idx_registros_fecha_evento" 
ON "public"."GERSSON_REGISTROS" (
  "FECHA_EVENTO" ASC
);
CREATE INDEX "idx_registros_cliente_fecha" 
ON "public"."GERSSON_REGISTROS" (
  "ID_CLIENTE" ASC,
  "FECHA_EVENTO" ASC
);
CREATE INDEX "idx_asesores_es_admin" 
ON "public"."GERSSON_ASESORES" (
  "ES_ADMIN" ASC
);
CREATE INDEX "idx_asesores_nombre" 
ON "public"."GERSSON_ASESORES" (
  "NOMBRE" ASC
);
CREATE INDEX "idx_asesores_id_tg" 
ON "public"."GERSSON_ASESORES" (
  "ID_TG" ASC
);
CREATE INDEX "idx_clientes_id_asesor" 
ON "public"."GERSSON_CLIENTES" (
  "ID_ASESOR" ASC
);
CREATE INDEX "idx_clientes_fecha_creacion" 
ON "public"."GERSSON_CLIENTES" (
  "FECHA_CREACION" ASC
);
CREATE INDEX "idx_clientes_nombre" 
ON "public"."GERSSON_CLIENTES" (
  "NOMBRE" ASC
);
CREATE INDEX "idx_clientes_estado" 
ON "public"."GERSSON_CLIENTES" (
  "ESTADO" ASC
);
CREATE INDEX "idx_clientes_asesor_fecha" 
ON "public"."GERSSON_CLIENTES" (
  "ID_ASESOR" ASC,
  "FECHA_CREACION" ASC
);
CREATE INDEX "idx_clientes_estado_fecha" 
ON "public"."GERSSON_CLIENTES" (
  "ESTADO" ASC,
  "FECHA_CREACION" ASC
);
CREATE INDEX "idx_reportes_estado_nuevo" 
ON "public"."GERSSON_REPORTES" (
  "ESTADO_NUEVO" ASC
);
CREATE INDEX "idx_reportes_fecha_seguimiento" 
ON "public"."GERSSON_REPORTES" (
  "FECHA_SEGUIMIENTO" ASC
);
CREATE INDEX "idx_reportes_completado" 
ON "public"."GERSSON_REPORTES" (
  "COMPLETADO" ASC
);
CREATE INDEX "idx_reportes_asesor_fecha_reporte" 
ON "public"."GERSSON_REPORTES" (
  "ID_ASESOR" ASC,
  "FECHA_REPORTE" ASC
);
CREATE INDEX "idx_reportes_asesor_fecha" 
ON "public"."GERSSON_REPORTES" (
  "ID_ASESOR" ASC,
  "FECHA_REPORTE" ASC
);
CREATE INDEX "idx_reportes_consolidado" 
ON "public"."GERSSON_REPORTES" (
  "consolidado" ASC
);
CREATE INDEX "idx_cliente_asesor" 
ON "public"."GERSSON_REPORTES" (
  "ID_CLIENTE" ASC,
  "ID_ASESOR" ASC
);
ALTER TABLE "public"."GERSSON_REGISTROS" ADD CONSTRAINT "GERSSON_REGISTROS_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "public"."GERSSON_CLIENTES" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."GERSSON_CLIENTES" ADD CONSTRAINT "GERSSON_CLIENTES_ID_ASESOR_fkey" FOREIGN KEY ("ID_ASESOR") REFERENCES "public"."GERSSON_ASESORES" ("ID") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "public"."GERSSON_REPORTES" ADD CONSTRAINT "GERSSON_REPORTES_ID_ASESOR_fkey" FOREIGN KEY ("ID_ASESOR") REFERENCES "public"."GERSSON_ASESORES" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."GERSSON_REPORTES" ADD CONSTRAINT "GERSSON_REPORTES_ID_CLIENTE_fkey" FOREIGN KEY ("ID_CLIENTE") REFERENCES "public"."GERSSON_CLIENTES" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."conversaciones" ADD CONSTRAINT "conversaciones_id_asesor_fkey" FOREIGN KEY ("id_asesor") REFERENCES "public"."GERSSON_ASESORES" ("ID") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "public"."conversaciones" ADD CONSTRAINT "ids" FOREIGN KEY ("id_asesor") REFERENCES "public"."GERSSON_ASESORES" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."conversaciones" ADD CONSTRAINT "id_asesor" FOREIGN KEY ("id_asesor") REFERENCES "public"."GERSSON_ASESORES" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."conversaciones" ADD CONSTRAINT "conversaciones_id_cliente_fkey" FOREIGN KEY ("id_cliente") REFERENCES "public"."GERSSON_CLIENTES" ("ID") ON DELETE SET NULL ON UPDATE NO ACTION;
