-- Crear tabla para gestión de VIPs
CREATE TABLE "public"."GERSSON_CUPOS_VIP" ( 
  "ID" SERIAL,
  "NOMBRE" VARCHAR(250),
  "CORREO" VARCHAR(250), 
  "WHATSAPP" VARCHAR(250) NOT NULL,
  "FECHA_IMPORTACION" TIMESTAMP DEFAULT NOW(),
  "ASESOR_ASIGNADO" INTEGER,
  "ESTADO_CONTACTO" VARCHAR(50) DEFAULT 'sin_asesor',
  "NOTAS" TEXT,
  "YA_ES_CLIENTE" BOOLEAN DEFAULT FALSE,
  "FECHA_CONTACTO" TIMESTAMP,
  "FECHA_ULTIMA_ACTUALIZACION" TIMESTAMP DEFAULT NOW(),
  "POSICION_CSV" INTEGER,
  "NIVEL_CONCIENCIA" VARCHAR(20) DEFAULT 'media',
  "ORIGEN_REGISTRO" VARCHAR(50) DEFAULT 'grupo_whatsapp',
  CONSTRAINT "GERSSON_CUPOS_VIP_pkey" PRIMARY KEY ("ID"),
  CONSTRAINT "fk_asesor_asignado" FOREIGN KEY ("ASESOR_ASIGNADO") REFERENCES "public"."GERSSON_ASESORES" ("ID")
);

-- Índices para optimizar búsquedas
CREATE INDEX idx_cupos_vip_whatsapp ON "public"."GERSSON_CUPOS_VIP" ("WHATSAPP");
CREATE INDEX idx_cupos_vip_asesor ON "public"."GERSSON_CUPOS_VIP" ("ASESOR_ASIGNADO");
CREATE INDEX idx_cupos_vip_estado ON "public"."GERSSON_CUPOS_VIP" ("ESTADO_CONTACTO");
CREATE INDEX idx_cupos_vip_posicion ON "public"."GERSSON_CUPOS_VIP" ("POSICION_CSV");
CREATE INDEX idx_cupos_vip_conciencia ON "public"."GERSSON_CUPOS_VIP" ("NIVEL_CONCIENCIA");
